//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using QLHS.Models.CustomAttributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BangDiem
    {
        public int MaBD { get; set; }
        public int MaHS { get; set; }
        public int Diem { get; set; }
        public int MaMon { get; set; }
        public string TenHS { get; set; }
        public string TenMon { get; set; }
        public object Clone()
        {
            return new BangDiem
            {
                MaBD = this.MaBD,
                MaHS = this.MaHS,
                Diem = this.Diem,
                MaMon = this.MaMon,
                TenHS = this.TenHS,
                TenMon = this.TenMon
            };
        }
        public virtual HocSinh HocSinh { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}