//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using QLHS.Models.CustomAttributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GiaoVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiaoVien()
        {
            this.Lops = new HashSet<Lop>();
            this.ViPhams = new HashSet<ViPham>();
            this.YeuCaus = new HashSet<YeuCau>();
        }

        public int MaGV { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required(ErrorMessage = "Tài Khoản là trường bắt buộc.")]
        public string TAIKHOAN { get; set; }
        [MatKhauValidation]
        [Required(ErrorMessage = "Mật Khẩu là trường bắt buộc.")]
        [StringLength(30, MinimumLength = 4)]
        public string MATKHAU { get; set; }
        [TenValidation]
        [Required(ErrorMessage = "Họ và Tên là trường bắt buộc.")]
        public string HoTenGV { get; set; }
        [GioiTinhValidation]
        [Required(ErrorMessage = "Mật Khẩu là trường bắt buộc.")]
        public string GioiTinh { get; set; }
        [NgaySinhValidation]
        [Required(ErrorMessage = "Ngày Sinh là trường bắt buộc.")]
        public string NgaySinh { get; set; }
        [StringLength(100, MinimumLength = 2)]
        [Required(ErrorMessage = "Địa Chỉ là trường bắt buộc.")]
        public string DiaChi { get; set; }
        [SDTValidation]
        [Required(ErrorMessage = "SĐT là trường bắt buộc.")]
        public string SDT { get; set; }
        [RoleValidation]
        [Required(ErrorMessage = "Vai Trò là trường bắt buộc.")]
        public string Role { get; set; }
        public bool TrangThai { get; set; }

        public object Clone()
        {
            return new GiaoVien
            {
                MaGV = this.MaGV,
                TAIKHOAN = this.TAIKHOAN,
                MATKHAU = this.MATKHAU,
                HoTenGV = this.HoTenGV,
                GioiTinh = this.GioiTinh,
                NgaySinh = this.NgaySinh,
                DiaChi = this.DiaChi,
                SDT = this.SDT,
                Role = this.Role,
            };
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lop> Lops { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViPham> ViPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCau> YeuCaus { get; set; }
    }
}