//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using QLHS.Models.CustomAttributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Runtime.CompilerServices;

    public partial class HocSinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocSinh()
        {
            this.BangDiems = new HashSet<BangDiem>();
            this.ViPhams = new HashSet<ViPham>();
        }

        public int MaHS { get; set; }
        [TenValidation]
        [Required(ErrorMessage = "Họ tên là trường bắt buộc.")]
        public string HoTen { get; set; }
        [Required(ErrorMessage = "Lớp là trường bắt buộc.")]
        public int Lop { get; set; }
        [GioiTinhValidation]
        [Required(ErrorMessage = "Giới tính là trường bắt buộc.")]
        public string GioiTinh { get; set; }
        [NgaySinhValidation]
        [Required(ErrorMessage = "Ngày Sinh là trường bắt buộc.")]
        public string NgaySinh { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required(ErrorMessage = "Địa chỉ là trường bắt buộc.")]
        public string DiaChi { get; set; }
        [Required(ErrorMessage = "Khóa là trường bắt buộc.")]
        public int Khoa { get; set; }
        [TenValidation]
        public string HoTenCha { get; set; }
        [TenValidation]
        public string HoTenMe { get; set; }
        [SDTValidation]
        [Required(ErrorMessage = "SĐT là trường bắt buộc.")]
        public string SDT { get; set; }
        [MatKhauValidation]
        [Required(ErrorMessage = "mật Khẩu là trường bắt buộc.")]
        public string MATKHAU { get; set; }
        public string TenLop { get; set; }
        public string TenKhoa { get; set; }

        public object Clone()
        {
            return new HocSinh
            {
                MaHS = this.MaHS,
                HoTen = this.HoTen,
                Lop = this.Lop,
                GioiTinh = this.GioiTinh,
                NgaySinh = this.NgaySinh,
                DiaChi = this.DiaChi,
                Khoa = this.Khoa,
                HoTenCha = this.HoTenCha,
                HoTenMe = this.HoTenMe,
                SDT = this.SDT,
                MATKHAU = this.MATKHAU,
            };
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangDiem> BangDiems { get; set; }
        public virtual Lop Lop1 { get; set; }
        public virtual KhoaHoc KhoaHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViPham> ViPhams { get; set; }
    }
}