//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using QLHS.Models.CustomAttributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Lop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lop()
        {
            this.HocSinhs = new HashSet<HocSinh>();
        }

        public int MaLop { get; set; }
        [TenLopValidationAttribute]
        [Required(ErrorMessage = "Tên lớp là trường bắt buộc.")]
        public string TenLop { get; set; }
        [Required(ErrorMessage = "Khối là trường bắt buộc.")]
        public int Khoi { get; set; }
        [NamValidationAttribute]
        [Required(ErrorMessage = "Năm là trường bắt buộc.")]
        public string NamHoc { get; set; }
        [SoLuongValidationAttribute]
        [Required(ErrorMessage = "Số Lượng là trường bắt buộc.")]
        public int Quantity { get; set; }
        [Required(ErrorMessage = "GVCN là trường bắt buộc.")]
        public int GVCN { get; set; }
        public string TenKhoi { get; set; }
        public string TenGVCN { get; set; }
        public int SLHT { get; set; }
        public object Clone()
        {
            return new Lop
            {
                MaLop = this.MaLop,
                TenLop = this.TenLop,
                Khoi = this.Khoi,
                NamHoc = this.NamHoc,
                Quantity = this.Quantity,
                GVCN = this.GVCN,
            };
        }
        public virtual GiaoVien GiaoVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
        public virtual Khoi Khoi1 { get; set; }
    }
}