//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDEntities : DbContext
    {
        public QLDEntities()
            : base("name=QLDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BangDiem> Scores { get; set; }
        public virtual DbSet<GiaoVien> Teachers { get; set; }
        public virtual DbSet<HocSinh> Students { get; set; }
        public virtual DbSet<KhoaHoc> Courses { get; set; }
        public virtual DbSet<Khoi> Grades { get; set; }
        public virtual DbSet<Lop> Classes { get; set; }
        public virtual DbSet<MonHoc> Subjects { get; set; }
        public virtual DbSet<ViPham> Mistakes { get; set; }
        public virtual DbSet<YeuCau> Requests { get; set; }
    }
}
