//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using QLHS.Models.CustomAttributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ViPham
    {
        public int MaVP { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required(ErrorMessage = "Lỗi là trường bắt buộc.")]
        public string LoiVP { get; set; }
        public int MaHS { get; set; }
        [MucDoValidationAttribute]
        [Required(ErrorMessage = "Mức Độ là trường bắt buộc.")]
        public int MucDo { get; set; }
        public int NguoiGhiNhan { get; set; }
        [Required(ErrorMessage = "Ngày ghi nhận là trường bắt buộc.")]
        public System.DateTime Ngay { get; set; }
        public string TenHS { get; set; }
        public string TenNguoiGhiNhan { get; set; }

        public object Clone()
        {
            return new ViPham
            {
                MaVP = this.MaVP,
                LoiVP = this.LoiVP,
                MaHS = this.MaHS,
                MucDo = this.MucDo,
                NguoiGhiNhan = this.NguoiGhiNhan,
                TenHS = this.TenHS,
                TenNguoiGhiNhan = this.TenNguoiGhiNhan
            };
        }

        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}