//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class YeuCau
    {
        public int MaYC { get; set; }
        public int MaGV { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required(ErrorMessage = "Nội dung là trường bắt buộc.")]
        public string NoiDung { get; set; }
        [StringLength(50, MinimumLength = 2)]
        [Required(ErrorMessage = "Lí do là trường bắt buộc.")]
        public string LiDo { get; set; }
        public bool TrangThai { get; set; }
        public string TenGVCN { get; set; }

        public object Clone()
        {
            return new YeuCau
            {
                MaYC = this.MaYC,
                MaGV = this.MaGV,
                NoiDung = this.NoiDung,
                LiDo = this.LiDo, 
                TrangThai = this.TrangThai,
                TenGVCN = this.TenGVCN
            };
        }

        public virtual GiaoVien GiaoVien { get; set; }
    }
}